import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/component/Sidebar";
import News from "@/component/News";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Horizon Alliance",
    description: "Generated by RCGroup",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div>
                    <Sidebar />
                </div>
                <div>{children}</div>
                <div>
                    <News />
                </div>
            </body>
        </html>
    );
}
